# Generated by Django 5.2.1 on 2025-05-21 17:08

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSession',
            fields=[
                ('id', apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.farmerprofile')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.vetprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('record_type', models.CharField(choices=[('SYMPTOM', 'Symptom'), ('TREATMENT', 'Treatment'), ('VACCINATION', 'Vaccination')], max_length=15)),
                ('notes', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='livestock.livestock')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetcare.caresession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='caresession',
            index=models.Index(fields=['status'], name='vetcare_car_status_709181_idx'),
        ),
        migrations.AddIndex(
            model_name='caresession',
            index=models.Index(fields=['vet'], name='vetcare_car_vet_id_61fefa_idx'),
        ),
    ]
