# Generated by Django 5.2.1 on 2025-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20),
        ),
    ]
