# Generated by Django 5.2.1 on 2025-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcare', '0002_alter_caresession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('CONCLUDED', 'Concluded')], default='PENDING', max_length=20),
        ),
    ]
