# Generated by Django 5.2.1 on 2025-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcare', '0003_alter_caresession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caresession',
            name='has_history',
            field=models.BooleanField(default=False),
        ),
    ]
