# Generated by Django 5.2.1 on 2025-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcare', '0004_caresession_has_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresession',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('CONCLUDED', 'Concluded')], default='PENDING', max_length=20, null=True),
        ),
    ]
