# Generated by Django 5.2.1 on 2025-06-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetcare', '0005_alter_caresession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresession',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CONCLUDED', 'Concluded')], default='PENDING', max_length=20, null=True),
        ),
    ]
