from .base import *

DEBUG = False
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SIMPLE_JWT["AUTH_COOKIE_SECURE"] = False

# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
