# Generated by Django 5.2.1 on 2025-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
