# Generated by Django 5.2.1 on 2025-06-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensordata_battery_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='SensorReading',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='blood_oxygen_level',
            new_name='blood_oxygen',
        ),
    ]
