# Generated by Django 5.2.1 on 2025-06-05 04:09

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('CARE_REQUEST_SENT', 'CARE_REQUEST_SENT'), ('CARE_REQUEST_ACCEPTED', 'CARE_REQUEST_ACCEPTED'), ('CARE_REQUEST_DECLINED', 'CARE_REQUEST_DECLINED'), ('CARE_REQUEST_CONCLUDED', 'CARE_REQUEST_CONCLUDED')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
