# Generated by Django 5.2.1 on 2025-06-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='actor',
        ),
    ]
