# Generated by Django 5.2.1 on 2025-05-21 17:08

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('birth_year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock_images/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('TREATING', 'Treating'), ('DEAD', 'Dead')], default='HEALTHY', max_length=20)),
            ],
            options={
                'ordering': ['tag_id', 'registered_at'],
            },
        ),
    ]
