# Generated by Django 5.2.1 on 2025-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='specie',
            new_name='breed',
        ),
        migrations.AlterField(
            model_name='livestock',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
