# Generated by Django 5.2.1 on 2025-05-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL),
        ),
    ]
