# Generated by Django 5.2.1 on 2025-05-18 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_rename_specie_livestock_breed_alter_livestock_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
