# Generated by Django 5.2.1 on 2025-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='health_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('TREATING', 'Treating'), ('DECEASED', 'Deceased')], default='HEALTHY', max_length=20),
        ),
    ]
