# Generated by Django 5.2.1 on 2025-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_livestock_is_archived_alter_livestock_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'ordering': ['tag_id', 'registered_at']},
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='livestock',
            name='health_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('TREATING', 'Treating'), ('DEAD', 'Dead')], default='HEALTHY', max_length=20),
        ),
    ]
