# Generated by Django 5.2.1 on 2025-07-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_alter_livestock_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
