# Generated by Django 5.2.1 on 2025-06-02 22:47

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', apps.core.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('VET', 'Vet'), ('ADMIN', 'Admin')], max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('otp_code', models.CharField(max_length=6)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
