# Generated by Django 5.2.1 on 2025-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetprofile',
            name='num_ratings',
        ),
        migrations.RemoveField(
            model_name='vetprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('ACCEPTED', 'Vet'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
