# Generated by Django 5.2.1 on 2025-05-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_vetprofile_num_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('VET', 'Vet'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
