# Generated by Django 5.2.1 on 2025-06-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
