# Generated by Django 5.2.1 on 2025-06-10 17:44

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_joined_pendinguser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_picture_upload_path),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
