# Generated by Django 5.2.1 on 2025-05-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_vetprofile_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Farmer Profile'},
        ),
        migrations.AlterModelOptions(
            name='vetprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Vet Profile'},
        ),
    ]
